core/urls.py
from django.urls import path, include
from .views import * 
from django.contrib.auth.decorators import login_required
from rest_framework import routers 

#Creamos rutas para la api
router = routers.DefaultRouter()
router.register('productos', ProductoViewset)
router.register('tipoproductos', TipoProductoViewset)
router.register('estados', EstadoViewset)
router.register('compras', CompraViewset)
# URLS
urlpatterns = [
    path('api/', include(router.urls)),
    path('', index , name="index"),
    path('indexapi', indexapi , name="indexapi"),
    path('about/', about , name="about"),
    path('blog/', blog , name="blog"),
    path('carrito/', login_required(carrito), name="carrito"),
    path('checkout/', checkout , name="checkout"),
    path('compra/<id>/', compra , name="compra"),
    path('detalle/', detalle , name="detalle"),
    path('historial/', login_required(historial) , name="historial"),
    path('oneProduct/<id>/', login_required(oneProduct) , name="oneProduct"),
    path('price/', price , name="price"),
    path('product/' , product , name="product"),
    path('prue/' , prue , name="prue"),
    path('seguimiento/', login_required(seguimiento), name="seguimiento"),
    path('seguimientoAdmin/', login_required(seguimientoAdmin), name="seguimientoAdmin"),
    path('registrar/', registrar , name="registrar"),
    path('suscripcion/', login_required(suscripcion) , name="suscripcion"),
    path('service/', service , name="service"),
    path('team/', team , name="team"),
    path('testimonio/', testimonio , name="testimonio"),
    
    #CRUD
    path('add/', login_required(add), name="add"),
    path('update/<id>/', update, name="update"),
    path('delete/<id>/', delete, name="delete"),

    path('deleteCarrito/<id>/', deleteCarrito, name="deleteCarrito"),
    path('agregarCompra/', agregarCompra, name="agregarCompra"),
    path('deleteProducto/<id>/', deleteProducto, name="deleteProducto"),
    path('deleteSuscripcion/<id>/', deleteSuscripcion, name="deleteSuscripcion"),
    
    path('addSeguimiento/', addSeguimiento, name="addSeguimiento"),
    path('updateEstado/<id>/', updateEstado, name="updateEstado"),
    #carrito

    #suscripcion
    path('adminSuscripcion/', login_required(adminSuscripcion) , name="adminSuscripcion"),

]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/' , include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.


class TipoProducto(models.Model):
  nombreTipo  = models.CharField(max_length=30);

  def __str__(self):
    return self.nombreTipo
    

class Producto(models.Model):
  nombre      = models.CharField(max_length=30)
  descripcion = models.CharField(max_length=60)
  precio      = models.IntegerField()
  stock       = models.IntegerField()
  imagen      = models.ImageField(null=True,blank=True)
  tipo        = models.ForeignKey(TipoProducto, on_delete=models.CASCADE) 

  def __str__(self):
    return self.nombre



class Cliente(models.Model):
  nombre     = models.CharField(max_length=40)
  apellido = models.CharField(max_length=40)
  user = models.OneToOneField('authentication.User', on_delete = models.CASCADE, verbose_name = 'Usuario', null=True)

  def __str__(self):
    return self.nombre

class Comentario(models.Model):
  resena      = models.CharField(max_length=60)
  user        = models.ForeignKey(Cliente, on_delete=models.CASCADE) 

  def __str__(self):
    return self.resena


class Carrito(models.Model):
  cliente    = models.ForeignKey(Cliente, on_delete=models.CASCADE) 
  producto    = models.ForeignKey(Producto, on_delete=models.CASCADE) 
  cantidad    = models.IntegerField()
  vigente = models.BooleanField()

  def __str__(self):
    return self.cliente.user.username


class Suscripcion(models.Model):
    cliente     = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    correo      = models.CharField(max_length=60)
    fecha       = models.DateField()

    def __str__(self):
        return self.cliente.user.username


class Estado(models.Model):
  nombreEstado  = models.CharField(max_length=50);

  def __str__(self):
    return self.nombreEstado
  


class Compra(models.Model):
    codigo = models.CharField(max_length=20)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=50)
    contacto = models.CharField(max_length=50)
    fecha = models.DateField()
    nombreEstado = models.ForeignKey(Estado, on_delete=models.CASCADE)

    def __str__(self):
        return self.codigo

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class ProductoForm(ModelForm):

    nombre      = forms.CharField(min_length=4,widget=forms.TextInput(attrs={"placeholder":"Ingrese Nombre"}))
    descripcion = forms.CharField(min_length=10,max_length=200,widget=forms.Textarea(attrs={"rows":4}))
    precio      = forms.IntegerField(min_value=0,widget=forms.NumberInput(attrs={"placeholder":"Ingrese Precio"}))
    stock       = forms.IntegerField(min_value=0,widget=forms.NumberInput(attrs={"placeholder":"Ingrese Stock"}))

    class Meta:
        model = Producto
        fields = '__all__'


class ClienteForm(ModelForm):

    user        = forms.CharField(min_length=3,widget=forms.TextInput(attrs={"placeholder":"Ingrese nombre de usuario"}))
    contrasena  = forms.CharField(min_length=5,widget=forms.TextInput(attrs={"placeholder":"Ingrese una contraseña"}))
    nombre      = forms.CharField(min_length=3,widget=forms.TextInput(attrs={"placeholder":"Ingrese nombre"}))
    apellido    = forms.CharField(min_length=3,widget=forms.TextInput(attrs={"placeholder":"Ingrese apellido"}))


    class Meta:
        model = Cliente
        exclude = ('contrasena','user')  



class CantidadForm (ModelForm):
    cantidad = forms.IntegerField(min_value=1, max_value=5, widget=forms.NumberInput(attrs={"placeholder":"Ingrese Cantidad"}))

    class Meta:
        model = Carrito
        fields = ['cantidad']


class CarritoForm (ModelForm):
    cliente = forms.CharField()
    producto = forms.IntegerField
    cantidad = forms.IntegerField(min_value=1, max_value=5, widget=forms.NumberInput(attrs={"placeholder":"Ingrese Cantidad"}))

    class Meta:
        model = Carrito
        fields = ['cantidad']


class SuscripcionForm (ModelForm):
    correo = forms.CharField(min_length=3,widget=forms.TextInput(attrs={"placeholder":"Ingrese su correo"}))

    class Meta:
        model = Suscripcion
        fields = ['correo']

class EstadoForm(ModelForm):
    class Meta:
        model = Compra
        fields = ['nombreEstado']



class envioForm (ModelForm):
    direccion = forms.CharField(min_length=3,widget=forms.TextInput(attrs={"placeholder":"Ingrese Dirección"}))
    contacto = forms.CharField(min_length=3,widget=forms.TextInput(attrs={"placeholder":"Ingrese Contacto"}))

    class Meta:
        model = Compra
        fields = ['direccion','contacto']

core/views.py
from django.shortcuts import render, redirect 
from .models import *
from .forms import *
from django.contrib import messages
import datetime
from datetime import date   
from datetime import timedelta
from rest_framework import viewsets
from .serializers import * 
import requests
import uuid
from django.contrib.auth.models import User,Group
from django.shortcuts import get_object_or_404
from authentication.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, login


def grupo_requerido(nombre_grupo):
    def decorator(view_fuc):
        @user_passes_test(lambda user: user.groups.filter(name=nombre_grupo).exists())
        def wrapper(request, *arg, **kwargs):
            return view_fuc(request, *arg, **kwargs)
        return wrapper
    return decorator

# @grupo_requerido('vendedor')


#grupo = Group.objects.get(name='cliente')
#user.groups.add(grupo)

# CREANDO UNA CLASE QUE VA A PERMITIR LA TRANSACCION

class ProductoViewset(viewsets.ModelViewSet):
      queryset = Producto.objects.all() 
     #queryset = Producto.objects.filter(tipo=1)
      serializer_class = ProductoSerializers


class TipoProductoViewset(viewsets.ModelViewSet):
      queryset = TipoProducto.objects.all()
      serializer_class = TipoProductoSerializers

class EstadoViewset(viewsets.ModelViewSet):
      queryset = Estado.objects.all()
      serializer_class = EstadoSerializers

class CompraViewset(viewsets.ModelViewSet):
      queryset = Compra.objects.all()
      serializer_class = CompraSerializers


#Productos

def index(request):
    productosAll = Producto.objects.all()[:4]
    data = {
        'listado': productosAll
    }
    return render(request, 'core/index.html', data)

#@grupo_requerido('admministradores')
def indexapi(request):
    respuesta = requests.get('http://127.0.0.1:8000/api/productos/')
    respuesta2 = requests.get('https://mindicador.cl/api')
    respuesta3 = requests.get('https://rickandmortyapi.com/api/character')
    #respuesta4 = request.get('http://127.0.0.1:8000/api/tipoproductos/')
    
    
    #transformacion del json

    productos = respuesta.json()
    monedas = respuesta2.json()
    aux = respuesta3.json()
    personajes = aux['results']


    data = {
        'listado': productos,
        'moneda' : monedas,
        'personajes' : personajes,
    }
    return render(request, 'core/indexapi.html', data)

def about(request):
    return render(request,('core/about.html'))

def blog(request):
    return render(request,('core/blog.html'))

@grupo_requerido('cliente')
def carrito(request):
    user = User.objects.filter(username=request.user.username).first()
    cliente = Cliente.objects.filter(user=user).first()
    CarritoCliente = Carrito.objects.filter(cliente=cliente, vigente = True)
    data = {
        'listado' : CarritoCliente,
        'form': envioForm()
    }

    respuesta = requests.get('https://mindicador.cl/api/dolar')
    monedas = respuesta.json()
    valor_usd = monedas['serie'] [0] ['valor']

    valor_carrito = sum(carrito.producto.precio*carrito.cantidad for carrito in CarritoCliente)

    try:
        suscripcionCliente = Suscripcion.objects.get(cliente=cliente)
    except Suscripcion.DoesNotExist:
        suscripcionCliente = None
    if suscripcionCliente != None:
        descuento = round(valor_carrito*0.05)
    else:
        descuento = 0

    valor_carritousd = valor_carrito/valor_usd
    total_descuentousd = descuento/valor_usd
    valor_total = valor_carrito-descuento
    valor_total = valor_total/valor_usd
    data['valor'] = round(valor_total, 2)
    data['descuento'] = round(total_descuentousd, 2)
    data['total_carrito'] = round(valor_carritousd, 2)

    return render(request, 'core/carrito.html', data)

def checkout(request):
    return render(request,('core/checkout.html'))

def detalle(request):
    return render(request,('core/detalle.html'))

def historial(request):
    user = User.objects.filter(username=request.user.username).first()
    cliente = Cliente.objects.filter(user=user).first()
    compra = []

    if cliente is not None:
        compra = Compra.objects.filter(cliente=cliente)

    data = {
        'listado': compra
    }
    
    return render(request,'core/historial.html', data)

def sesion(request):
    return render(request,('core/sesion.html'))



@grupo_requerido('cliente')
def suscripcion(request):
    user = request.user
    cliente = Cliente.objects.get(user=user)

    respuesta = requests.get('https://mindicador.cl/api/dolar')
    monedas = respuesta.json()
    valor_usd = monedas['serie'][0]['valor']

    data = {'form': None}

    if request.method == 'POST':
        formulario = SuscripcionForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            suscripcion = formulario.save(commit=False)
            suscripcion.cliente = cliente
            monto_ingresado = formulario.cleaned_data['monto']
            suscripcion.monto = monto_ingresado
            suscripcion.save()
            valor_total = monto_ingresado / valor_usd
            data['form'] = formulario
            data['valor'] = round(valor_total, 2)

    else:
        formulario = SuscripcionForm(initial={'monto': 1000})
        data['form'] = formulario

    return render(request, 'core/suscripcion.html', data)

@grupo_requerido('cliente')
def suscripcion(request):
    user = request.user
    cliente = Cliente.objects.get(user=user)

    data = {'form': None}

    if request.method == 'POST':
        formulario = SuscripcionForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            suscripcion = formulario.save(commit=False)
            suscripcion.cliente = cliente
            suscripcion.fecha = date.today() + timedelta(days=30)  # Fecha por defecto: fecha actual + 30 días
            suscripcion.save()
            data['form'] = formulario
            #data['mensaje'] = 'Gracias por suscribirte.'

    else:
        formulario = SuscripcionForm()
        data['form'] = formulario

    return render(request, 'core/suscripcion.html', data)







@grupo_requerido('cliente')
def oneProduct(request, id):
    producto = Producto.objects.get(id=id)
    user = User.objects.filter(username=request.user.username).first()
    cliente = Cliente.objects.get(user=user)

    data = {
        'producto': producto,
        'user': request.user.username,
        'form': CantidadForm(initial={'cantidad': 1})
    }

    if request.method == 'POST':
        formulario = CantidadForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            try:
                carritoCP = Carrito.objects.get(cliente=cliente, producto=producto, vigente=True)
                cantidad_stock = carritoCP.cantidad + producto.stock
                cantidad_agregada = int(formulario.cleaned_data["cantidad"])

                if cantidad_agregada > cantidad_stock:
                    cantidad_agregada = cantidad_stock

                carritoCP.cantidad = carritoCP.cantidad + cantidad_agregada
                carritoCP.save()
                producto.stock = producto.stock - cantidad_agregada
            except Carrito.DoesNotExist:
                cantidad_agregada = int(formulario.cleaned_data["cantidad"])
                if cantidad_agregada > producto.stock:
                    cantidad_agregada = producto.stock

                carrito = Carrito.objects.create(cliente=cliente, producto=producto, cantidad=cantidad_agregada, vigente=True)
                producto.stock = producto.stock - cantidad_agregada

    producto.save()

    return render(request, 'core/oneProduct.html', data)

    
 


def price(request):
    return render(request,('core/price.html'))

def product(request):
    productosAll = Producto.objects.all()

    data = {
        'listado': productosAll
    }
    return render(request, 'core/product.html', data)

def prue(request):
    carritosAll = Producto.objects.all()
    data = {
        'listado': carritosAll
    }
    return render(request,'core/prue.html', data)

#@grupo_requerido('administradores')
#@grupo_requerido('cliente')


def seguimientoAdmin(request):
    compras = Compra.objects.all()

    data = {
        'listado': compras
    }

    return render(request, 'core/seguimientoAdmin.html', data)





def seguimiento(request):
    user = User.objects.filter(username=request.user.username).first()
    cliente = Cliente.objects.filter(user=user).first()
    compra = []

    if cliente is not None:
        compra = Compra.objects.filter(cliente=cliente)

    data = {
        'listado': compra
    }

    return render(request, 'core/seguimiento.html', data)




def registrar(request):
    data = {
        'form' : ClienteForm()
    }

    if request.method == 'POST':
        formulario = ClienteForm(request.POST, files=request.FILES) 
        if formulario.is_valid():
            nombre = formulario.cleaned_data['nombre']
            apellido = formulario.cleaned_data['apellido']
            usuario = formulario.cleaned_data['user']
            contrasena = formulario.cleaned_data['contrasena']
            # Creamos un usuario de tipo cliente
            user = User()
            user.username = usuario
            user.set_password(contrasena)
            user.save()
            cliente = Cliente.objects.create(nombre=nombre, apellido=apellido, user=user)
            cliente.save()
            data['msj'] = "Cliente guardado correctamente"
            messages.success(request, "Cliente almacenado correctamente")
            grupo = Group.objects.get(name='cliente')
            user.groups.add(grupo)
        return render(request,'core/index.html')

    return render(request,'core/registrar.html', data)


def service(request):
    return render(request,('core/service.html'))

def team(request):
    return render(request,('core/team.html'))
    
def testimonio(request):
    return render(request,('core/testimonio.html'))

#CRUD

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
<!-- NAVBAR INICIO ACTIVE -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
    <a href="{% url 'index'%}" class="navbar-brand ms-lg-5">
        <h1 class="m-0 text-uppercase text-dark"><i class="bi bi-shop fs-1 text-primary me-3"></i>Petshop</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-0">
            {% if user.is_authenticated %}
            <a href="#"class= "nav-link">Bienvenido: {{ user.username }}</a>
            <a href="{% url 'logout' %}"class= "nav-link">Cerrar sesion</a>
            {% else %}
            <a href="{% url 'login' %}"class= "nav-link">Ingresar</a>
            {% endif %}
            <a href="{% url 'index'%}" class="nav-item nav-link active">Inicio</a>
            <a href="{% url 'historial'%}" class="nav-item nav-link ">compras</a>

            <a href="{% url 'product'%}" class="nav-item nav-link ">Producto</a>
            {% if user.is_superuser %}
            <a href="{% url 'seguimientoAdmin' %}" class="nav-item nav-link ">Seguimiento</a>
            {% else %}
            <a href="{% url 'seguimiento' %}" class="nav-item nav-link ">Seguimiento</a>
            {% endif %}
			{% if user.cliente.suscripcion_set.exists %}
            <a href="{% url 'adminSuscripcion'%}" class="nav-item nav-link ">Suscripcion</a>
            {% elif user.is_authenticated %}
            <a href="{% url 'suscripcion'%}" class="nav-item nav-link ">Suscribete</a>    
            {% endif %}
            <div class="nav-item dropdown">

                <!-----------------------SOLUCIONAR DROP DOWN-------------------------->
                <!--MODIFICAR NOMBRES-->
                <!--<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu m-0">
                    <a href="{% url 'team' %}" class="dropdown-item">The Team</a>
                    <a href="{% url 'testimonio' %}" class="dropdown-item">Testimonial</a>
                    <a href="{% url 'blog' %}" class="dropdown-item">Blog Grid</a>
                    <a href="{% url 'detalle' %}" class="dropdown-item">Blog Detail</a>
                </div>-->
                <!-------------------------------------------------------------------->
            </div>
            <a href="{% url 'carrito' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">Carrito <i class="bi bi-cart"></i></a>
        </div>
    </div>
</nav>
<!-- NAVBAR FIN -->


<!-- ABOUT INICIO-->
<div class="container-fluid py-5">
	<div class="container">
			<div class="row gx-5">
					<div class="col-lg-5 mb-5 mb-lg-0" style="min-height: 500px;">
							<div class="position-relative h-100">
									<img class="position-absolute w-100 h-100 rounded" src="{% static 'core/img/about.jpg'%}" style="object-fit: cover;">
							</div>
					</div>
					<div class="col-lg-7">
							<div class="border-start border-5 border-primary ps-5 mb-5">
									<h6 class="text-primary text-uppercase">Mas de nosotros</h6>
									<h1 class="display-5 text-uppercase mb-0">Mantenemos a sus mascotas felices todo el tiempo</h1>
							</div>
							<h4 class="text-body mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, esse.</h4>
							<div class="bg-light p-4">
									<ul class="nav nav-pills justify-content-between mb-3" id="pills-tab" role="tablist">
											<li class="nav-item w-50" role="presentation">
													<button class="nav-link text-uppercase w-100 active" id="pills-1-tab" data-bs-toggle="pill"
															data-bs-target="#pills-1" type="button" role="tab" aria-controls="pills-1"
															aria-selected="true">Nuestra misión</button>
											</li>
											<li class="nav-item w-50" role="presentation">
													<button class="nav-link text-uppercase w-100" id="pills-2-tab" data-bs-toggle="pill"
															data-bs-target="#pills-2" type="button" role="tab" aria-controls="pills-2"
															aria-selected="false">Nuestra visión</button>
											</li>
									</ul>
									<div class="tab-content" id="pills-tabContent">
											<div class="tab-pane fade show active" id="pills-1" role="tabpanel" aria-labelledby="pills-1-tab">
													<p class="mb-0">Tempor erat elitr at rebum at at clita aliquyam consetetur. Diam dolor diam ipsum et, tempor voluptua sit consetetur sit. Aliquyam diam amet diam et eos sadipscing labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor consetetur takimata eirmod, dolores takimata consetetur invidunt magna dolores aliquyam dolores dolore. Amet erat amet et magna</p>
											</div>
											<div class="tab-pane fade" id="pills-2" role="tabpanel" aria-labelledby="pills-2-tab">
													<p class="mb-0">Tempor erat elitr at rebum at at clita aliquyam consetetur. Diam dolor diam ipsum et, tempor voluptua sit consetetur sit. Aliquyam diam amet diam et eos sadipscing labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor consetetur takimata eirmod, dolores takimata consetetur invidunt magna dolores aliquyam dolores dolore. Amet erat amet et magna</p>
											</div>
									</div>
							</div>
					</div>
			</div>
	</div>
</div>
<!-- ABOUT FIN -->
{% endblock %}

core/templates/core/addProduct.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}

{% endblock %}
{% block contenido %}
<div class="container">
    <div class="row">
        <div class="col-12 m-5">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form | crispy }}
                </table>
                <input type="submit" class="btn btn-success" value="Guardar">
                <a href="{% url 'index' %}"><i class="fas fa-angle-left me-2"></i>Volver</a>
            </form>
    <br><br><br>
        </div>
    </div>
</div>

{% endblock %}
{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% if messages %} 
    {% for aux in messages %} 
    <script>
      Swal.fire({
      title: 'Confirmación',
      text: '{{ aux }}',
      icon: 'success',
      showCancelButton: false,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Confirmar'
    })
    </script>
    {% endfor %} 
{% endif %}
{% endblock %}

core/templates/core/addSeguimiento.html
{% extends 'core/base.html' %} 
{% load static %} 
{% load crispy_forms_tags %} 

{% block css %} 
{% endblock %} 

{% block contenido %}
<div class="container">
  <div class="row">
    <div class="col-12 m-5">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ form | crispy }}
        </table>
        <input type="submit" class="btn btn-success" value="Guardar" />
        <a href="{% url 'index' %}"><i class="fas fa-angle-left me-2"></i>Volver</a>
      </form>
      <br /><br /><br />
    </div>
  </div>
</div>


{% endblock %} 

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% if messages %} 
    {% for aux in messages %} 
    <script>
      Swal.fire({
      title: 'Confirmación',
      text: '{{ aux }}',
      icon: 'success',
      showCancelButton: false,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Confirmar'
    })
    </script>
    {% endfor %} 
{% endif %}
{% endblock %}

core/templates/core/blog.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
  <h1>AQUI VA EL CONTENIDO BLOG</h1>
{% endblock %}

core/templates/core/price.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
  <h1>AQUI VA EL CONTENIDO PRICE</h1>
{% endblock %}

core/templates/core/registrar.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}

{% endblock %}
{% block contenido %}
<section class="vh-10" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="container">
            <div class="row">
                <div class="col-12 m-4">
                      <form action="" method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="card text-black" style="border-radius: 25px;">
                            <div class="card-body p-md-5">
                              <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                  <div class="">
                                    <img src="{% static 'core/img/regi.png'%}"
                                      class="card-img-top" alt="image">
                                  </div>
                                  <p class="text-center h1 fw-bold">Registrate</p>
                                  <form class="mx-1 mx-md-4">
                                    <table>
                                        {{ form | crispy }}
                                        <div class="form-check d-flex justify-content-center mb-5">
                                          <label class="form-check-label" for="form2Example3">
                                            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                                            Estoy de acuerdo con los términos de servicio 
                                          </label>
                                        </div>
                                    </table>
                                    <input type="submit" class="btn btn-success" value="Registrarse">
                                    <a href="{% url 'login' %}"><i class="fas fa-angle-left me-2"></i>Volver</a>
                                  </form>
                                </div>
                              </div>
                            </div>
                          </div>
                      </form>

                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}
{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11%22%3E"></script>
{% if messages %} 
    {% for aux in messages %} 
    <script>
      Swal.fire({
      title: 'Confirmación',
      text: '{{ aux }}',
      icon: 'success',
      showCancelButton: false,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Confirmar'
    })
    </script>
    {% endfor %} 

    {% endif %}
{% endblock %}

core/templates/core/team.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
  <h1>AQUI VA EL CONTENIDO TEAM</h1>
{% endblock %}